### ISSUE TITLE
Functions inside of preprocessor ifdefs ignored (C)

### ISSUE THREAD

**Issue by AlexSutila** [eckon/treesitter-current-functions#15]
Hello! First of all, I've really been enjoying using this plugin, it's only been about a day and I'm already finding myself using it a ton. However, I am currently noticing that certain functions are being ignored in this sort of a scenario:

![image](https://github.com/eckon/treesitter-current-functions/assets/96510931/969e3411-589b-4eac-8d91-6926f9b32d95)

Basically just allowing for certain features to be included or excluded entirely from the build if a specific make target is specified. As seen in the screenshot below, it does not list bar():

![image](https://github.com/eckon/treesitter-current-functions/assets/96510931/f91e16a6-396f-4717-a3bc-b9db8d8cd298)

What TSPlaygroundToggle displays for the code above:

```
preproc_include [0, 0] - [1, 0]
  path: system_lib_string [0, 9] - [0, 18]
preproc_ifdef [2, 0] - [8, 6]
  name: identifier [2, 7] - [2, 22]
  function_definition [3, 0] - [5, 1]
    type: primitive_type [3, 0] - [3, 4]
    declarator: function_declarator [3, 5] - [3, 10]
      declarator: identifier [3, 5] - [3, 8]
      parameters: parameter_list [3, 8] - [3, 10]
    body: compound_statement [3, 11] - [5, 1]
      expression_statement [4, 4] - [4, 20]
        call_expression [4, 4] - [4, 19]
          function: identifier [4, 4] - [4, 10]
          arguments: argument_list [4, 10] - [4, 19]
            string_literal [4, 11] - [4, 18]
              string_content [4, 12] - [4, 15]
              escape_sequence [4, 15] - [4, 17]
  alternative: preproc_else [6, 0] - [8, 0]
    preproc_function_def [7, 0] - [8, 0]
      name: identifier [7, 8] - [7, 11]
      parameters: preproc_params [7, 11] - [7, 13]
comment [8, 7] - [8, 28]
function_definition [10, 0] - [12, 1]
  type: primitive_type [10, 0] - [10, 4]
  declarator: function_declarator [10, 5] - [10, 10]
    declarator: identifier [10, 5] - [10, 8]
    parameters: parameter_list [10, 8] - [10, 10]
  body: compound_statement [10, 11] - [12, 1]
    expression_statement [11, 4] - [11, 20]
      call_expression [11, 4] - [11, 19]
        function: identifier [11, 4] - [11, 10]
        arguments: argument_list [11, 10] - [11, 19]
          string_literal [11, 11] - [11, 18]
            string_content [11, 12] - [11, 15]
            escape_sequence [11, 15] - [11, 17]
function_definition [14, 0] - [19, 1]
  type: primitive_type [14, 0] - [14, 3]
  declarator: function_declarator [14, 4] - [14, 32]
    declarator: identifier [14, 4] - [14, 8]
    parameters: parameter_list [14, 8] - [14, 32]
      parameter_declaration [14, 9] - [14, 17]
        type: primitive_type [14, 9] - [14, 12]
        declarator: identifier [14, 13] - [14, 17]
      parameter_declaration [14, 19] - [14, 31]
        type: primitive_type [14, 19] - [14, 23]
        declarator: pointer_declarator [14, 24] - [14, 31]
          declarator: array_declarator [14, 25] - [14, 31]
            declarator: identifier [14, 25] - [14, 29]
  body: compound_statement [15, 0] - [19, 1]
    expression_statement [16, 4] - [16, 10]
      call_expression [16, 4] - [16, 9]
        function: identifier [16, 4] - [16, 7]
        arguments: argument_list [16, 7] - [16, 9]
    expression_statement [17, 4] - [17, 10]
      call_expression [17, 4] - [17, 9]
        function: identifier [17, 4] - [17, 7]
        arguments: argument_list [17, 7] - [17, 9]
    return_statement [18, 4] - [18, 13]
      number_literal [18, 11] - [18, 12]
```

I cloned this repo myself and tried checking for `preproc_ifdef` and `preproc_if` in the following snippet below and was able to get bar() to show as expected:

https://github.com/eckon/treesitter-current-functions/blob/4d0f464fe6aea3bbbcaae4ed3a9b3f216bf8eb9d/lua/tscf/init.lua#L115-L118

Just inserted these two lines to be more specific:

```lua
       or tsnode:type() == "preproc_ifdef"
       or tsnode:type() == "preproc_if"
```

The code I showed above doesn't have a preprocessor if anywhere, but a similar issue occurs if I try to replace the `ifdef` with an `if` hence why I added the second line. Additionally, TSPlaygroundToggle also lists `ifndef` as `preproc_ifdef` so this also made bar() appear just fine in the scenario where the `ifdef` is replaced with an `ifndef`.

**Comment by eckon** [comment]
Hey @AlexSutila, thanks for checking out my plugin and enjoying it :)

I rarely use `c`, but if the given example is what you want, then I can try to add what you specified (maybe thats all whats really needed) and a new version should be here soon.

Also always open to merge a PR in case you want to extend it yourself, if you do so please add the testing case, so this plugin does not regress later on.

**Comment by eckon** [comment]
@AlexSutila small update, your snippet worked fine :) I also added the `preproc` for `else` just to have (hopefully) all needed cases for these c definitions.

Ignore the many commits, I had to fight with my (shitty) self implemented snapshot tests. It seems like neovim or treesitter changed how they return/print data, so my local generated expected data (on nightly neovim) did not align with the tests which use the latest stable. This took me too long to figure out :P

Hope this addition is as you expect, otherwise feel free to re-/open an/another issue or create a pr, have a nice day :)

**Comment by AlexSutila** [comment]
Thanks! Both C and C++ are two of the languages I use most. I haven't noticed any other issues with C, but after spending a good amount of time in a C++ project earlier today I noticed a few more issues, so I might take you up on that PR c:

I was able to wrap my head around your test scripts, so if I do get around to it I should also be able to extend those appropriately
