### ISSUE TITLE
Use of deprecated treesitter code - Will be removed in Nvim 0.10

### ISSUE THREAD

**Issue by sf1tzp** [eckon/treesitter-current-functions#5]
Hello! First off, thanks for making this plugin, I find it to be really useful.

I noticed this warning after upgrading recently:
```
vim.treesitter.query.get_node_text() is deprecated, use vim.treesitter.get_node_text() instead. :help deprecated
This feature will be removed in Nvim version 0.10
```
Looks like a pretty straightforward fix, I only see this in a few places
```
 >  grep get_node_text
lua/tscf/init.lua
46:  local function_name = vim.treesitter.query.get_node_text(function_name_node, 0)
49:  local line_content = vim.treesitter.query.get_node_text(node, 0)
130:      local structure_name = vim.treesitter.query.get_node_text(structure_name_node, 0)
```

I can try to find some time to work on this if you like. I'll create a PR when I have something ready.

**Comment by eckon** [comment]
Hey, thanks for opening an issue and generally for using the plugin :).

~~I do not get that error message in my current neovim installation (just downloaded the latest version), but after some digging, I found the reference in the 0.9 news (the normal `:h news` sadly points to the newest when using latest - which does not have changes from 0.9).~~
**EDIT: Message was just hidden**

https://github.com/neovim/neovim/blob/master/runtime/doc/news-0.9.txt#L317

https://github.com/neovim/neovim/commit/040f1459849ab05b04f6bb1e77b3def16b4c2f2b#diff-e682fc63c5b105e3eab956c380e8abf951a1b0d14fea03ae0f079bd490686e77L322

It also seems like the return changed a bit, it should not make a difference, but could be a reason for some small bugs:
https://github.com/neovim/neovim/blob/master/runtime/doc/news-0.9.txt#L51

I will have a look and update the plugin, as you said it should not be much of a problem

**Comment by eckon** [comment]
@f1tzpatrick merged the fix. the message should now be gone.
I quickly tested the plugin, and I did not see any problems or changes in behavior.

Thanks again for the issue and have a nice day :)

**Comment by sf1tzp** [comment]
Wow, that was quick! Have a nice weekend!
