### ISSUE TITLE
No functions found in C Code

### ISSUE THREAD

**Issue by SethBarberee** [eckon/treesitter-current-functions#9]
With following sample code
```c
bool8 sub_8039880(void)
{
  return (CountMailType(WONDER_MAIL_TYPE_SOS) != 0 || CountMailType(WONDER_MAIL_TYPE_OKD) != 0 || sub_8011C1C() == 2);
}
```

Produces following treesitter:
```
function_definition [176, 0] - [179, 1]
  type: type_identifier [176, 0] - [176, 5]
  declarator: function_declarator [176, 6] - [176, 23]
    declarator: identifier [176, 6] - [176, 17]
    parameters: parameter_list [176, 17] - [176, 23]
      parameter_declaration [176, 18] - [176, 22]
        type: primitive_type [176, 18] - [176, 22]
  body: compound_statement [177, 0] - [179, 1]
    return_statement [178, 2] - [178, 118]
      parenthesized_expression [178, 9] - [178, 117]
        binary_expression [178, 10] - [178, 116]
          left: binary_expression [178, 10] - [178, 94]
            left: binary_expression [178, 10] - [178, 50]
              left: call_expression [178, 10] - [178, 45]
                function: identifier [178, 10] - [178, 23]
                arguments: argument_list [178, 23] - [178, 45]
                  identifier [178, 24] - [178, 44]
              right: number_literal [178, 49] - [178, 50]
            right: binary_expression [178, 54] - [178, 94]
              left: call_expression [178, 54] - [178, 89]
                function: identifier [178, 54] - [178, 67]
                arguments: argument_list [178, 67] - [178, 89]
                  identifier [178, 68] - [178, 88]
              right: number_literal [178, 93] - [178, 94]
          right: binary_expression [178, 98] - [178, 116]
            left: call_expression [178, 98] - [178, 111]
              function: identifier [178, 98] - [178, 109]
              arguments: argument_list [178, 109] - [178, 111]
            right: number_literal [178, 115] - [178, 116]
```

Your code seems to assume `function_definition` has a higher level node so disregards/skips this. 
https://github.com/eckon/treesitter-current-functions/blob/9696f949f0e27bd1d8034c3245180f977461f7b7/lua/tscf/init.lua#L92

I tried with some Go code and there we see a similar signature defined as `function_declaration` and shows up just fine in the plugin.

**Comment by eckon** [comment]
Hey, yeah never tested c. There are many ways for treesitter to mark nodes which are valid functions.
I did not look into this case yet, but it sounds like this might be in conflict with the current implementation for other languages.

I will have a look into it when I find the time, thanks for the issue :)

**Comment by eckon** [comment]
@SethBarberee added some basic logic for this case. It was "skipped" before as the signature for classes and generally deeply nested constructs need to be handled.
For example see the `js` example file, the methods in the class would otherwise not be found.

As far as I can see it does not result in any conflicts for any of my examples.

If this does not fix the problem, feel free to reopen and comment :)

**Comment by SethBarberee** [comment]
Yup, seems to have fixed my C code and python as well.
